### ISSUE TITLE
BUG: "string" is not a valid rule name

### ISSUE THREAD

**Issue by matak** [rindeal/allegro-php-client#6] opened 2016-06-20 16:06 UTC
Respect\Validation\Exceptions\ComponentException

"string" is not a valid rule name

bug is somewhere here

ApiCredentials
                     Validator::string()->noWhitespace()->notEmpty()->length(4)->assert($value);

**Comment by rindeal** [comment] 2016-06-21 16:46
caused by an update in respect/validation (1.0.* -> 1.1.*), fixed in https://github.com/rindeal/allegro-php-client/commit/81e326e5f36abc135dfe49fa7aa17bb77f476c42

**Closed by rindeal** 2016-06-21 16:46 UTC
